TOPIC_DRIVE_PARAMETERS = "/input/drive_param/autonomous"
TOPIC_SCAN = "/scan"
TOPIC_CRASH = "/crash"
TOPIC_GAZEBO_MODEL_STATE = "/gazebo/model_states"
TOPIC_EPISODE_RESULT = "/reinforcement_learning/episode_result"
TOPIC_GAZEBO_STATE_TELEMETRY = "/gazebo/state_telemetry"
TOPIC_DRIVE_PARAMETERS_WF2RL = "/input/drive_param/wf2rl"
